### ISSUE TITLE
Hello. How to build with sqlite?

### ISSUE THREAD

**Issue by Petrunak** [GRRedWings/python3-android#34]
Hello. I have a problem after compile it.
I need to add sqlite3 to this.
How can i do it?
I tried to add this in docker-build.sh, but i get a problem.
My docker file :
`#!/bin/bash

set -e
set -x

apt-get update -y
apt-get install -y autoconf-archive autoconf automake cmake gawk gettext git gcc make patch pkg-config libsqlite3-dev
pip install pysqlite3

export ANDROID_NDK=/android-ndk

if [ ! -d "$ANDROID_NDK" ] ; then
    # In general we don't want download NDK for every build, but it is simpler to do it here
    # for CI builds
    NDK_VER=r25b
    apt-get install -y wget zip
    wget --no-verbose https://dl.google.com/android/repository/android-ndk-$NDK_VER-linux.zip
    unzip android-ndk-${NDK_VER}-linux.zip
    ANDROID_NDK=/android-ndk-$NDK_VER
fi

cd /python3-android

./build.sh "$@"`

I have this error on my phone
`SyntaxError: invalid syntax
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/local/tmp/build/usr/lib/python3.11/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/data/local/tmp/build/usr/lib/python3.11/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
>>>`
Where can i add sqlite3 module?

**Comment by Soft-Buddy** [comment]
@GRRedWings Any news about this issue?

**Comment by GRRedWings** [comment]
I haven't spent a lot of time working on this. I know the most recent version of Python broke the build.  If you look at the API26 branch, I feel that is pretty stable and you could try to build off that and see if you have any better luck.

**Comment by Soft-Buddy** [comment]
@GRRedWings 
```
Python 3.12.1 (main, Feb 23 2024, 21:00:23) [Clang 17.0.2 (https://android.googlesource.com/toolchain/llvm-project d9f89f4d1 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "/data/data/org.softbuddy.pythonx/files/usr/lib/python3.12/datetime.py", line 2, in <module>
    from _datetime import *
ImportError: dlopen failed: cannot locate symbol "PyTuple_Type" referenced by "/data/data/org.softbuddy.pythonx/files/usr/lib/python3.12/lib-dynload/_datetime.cpython-312.so"...
```

**Comment by Soft-Buddy** [comment]
I kind of faced a similar error in previous time while cross compiling some python modules (namely, numpy) which i fixed later by linking the libraries with libpython.... .so which fixed the issue
